### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by ytaylordev** [Adalab/modulo-1-evaluacion-final-manuelainclan#1]
Muy buen trabajo @manuelainclan  !!!

Aquí tienes unos consejos para mejorar tu ejercicio:

- [x] HTML: Esta etiqueta `<p>` debe ser con minúscula: https://github.com/Adalab/modulo-1-evaluacion-final-manuelainclan/blob/025ec04db00d42767c32a65051013ac36599f517/src/html/partials/hero.html#L4 
- [x] HTML > HERO: El texto del título del hero debe ser: Hasta un 50% de descuento (con la primera letra en mayúsculas y el resto en minúsculas, luego cambia a mayúsculas con la propiedad `text-transform`).

Ánimo y si tienes cualquier duda avísame!!!

> Con cada mejora que hagas, marcarla como completada en este issue y su súbela a este repo.

> Por favor no cierres este issue, ya lo haremos nosotros.

**Comment by manuelainclan** [comment]
Gracias por las correciones!! por ponerlo todo en mayúsculas puse mal el `<p>`
